---
- name: Configure Docker group and user permissions
  hosts: arch_hosts
  become: yes
  vars:
    user: "{{ ansible_user }}"
  tasks:
    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes
