---
- name: Setup example Python development environment for ML
  hosts: arch_hosts
  become: true
  vars:
    user: "{{ ansible_user }}"
    requirements:
      - pyspark==4.0.1
      - numpy==2.3.3
      - pandas==2.3.3
      - notebook==7.4.7
      - mlflow==3.4.0
      - apache-airflow==3.1.0
      - pyright==1.1.406
      - opencv-python
  tasks:
    - name: Create workspace/example-ml directory
      file:
        path: /home/{{ user }}/workspace/example-ml
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Ensure python-virtualenv is installed
      package:
        name: python-virtualenv
        state: present

    - name: Create Python virtual environment
      command: python3 -m venv /home/{{ user }}/workspace/example-ml/venv
      args:
        creates: /home/{{ user }}/workspace/example-ml/venv
      become: false
    
    - name: Set permissions for venv directory
      file:
        path: /home/{{ user }}/workspace/example-ml/venv
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Create requirements.txt file
      copy:
        dest: /home/{{ user }}/workspace/example-ml/requirements.txt
        content: "{{ requirements | join('\n') }}\n"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Install Python packages in virtual environment
      pip:
        requirements: /home/{{ user }}/workspace/example-ml/requirements.txt
        virtualenv: /home/{{ user }}/workspace/example-ml/venv
