---
- name: Configure Docker group and user permissions
  hosts: arch_hosts
  become: yes
  vars:
    user: "{{ ansible_user }}"
  tasks:
    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes
        
#    - name: Reload permissions
#      ansible.builtin.command:
#        cmd: newgrp docker
#      environment:
#        SHELL: /bin/bash
        
    - name: Add Docker aliases to .bashrc
      ansible.builtin.blockinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        block: |
          alias docker_s="sudo systemctl start docker.service"
          alias docker_c_a="docker system prune -a --volumes"
          alias docker_c_v="docker volume prune -f"
          alias docker_c_n="docker network prune -f"
          alias docker_c_c="docker container prune -f"
          alias docker_c_i="docker image prune -a -f"
          alias docker_ps="docker ps -a"
          alias docker_stop='[ -n "$(docker ps -qa)" ] && docker stop $(docker ps -qa)'
          alias docker_rm='[ -n "$(docker ps -qa)" ] && docker stop $(docker ps -qa) && docker rm $(docker ps -aq) && docker volume prune -f && docker network prune -f'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Docker aliases"
        create: yes
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"       
